USE stock;
WITH SubQuery
AS
(
SELECT
	*,
	ROUND(stdev(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW),0) as StandardDeviation,
	AVG(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW) AS THREE_MO_AVG,
	(intVol-AVG(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW))/ROUND(stdev(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW),0) AS NumStdDevs,
	CASE
		WHEN (intVol-AVG(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW))/ROUND(stdev(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW),0)
		> 2
			AND decAdjClose > LAG(decAdjClose,1) OVER (PARTITION BY strTick ORDER BY dtDate)
		THEN 1
		ELSE 0
	END AS BUY_Indicator,
	CASE
		WHEN (intVol-AVG(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW))/ROUND(stdev(intVol) OVER (PARTITION BY strTick ORDER BY dtDate ROWS BETWEEN 63 PRECEDING AND CURRENT ROW),0)
		< -1
			AND decAdjClose < LAG(decAdjClose,1) OVER (PARTITION BY strTick ORDER BY dtDate)
		THEN 1
		ELSE 0
	END AS SELL_Indicator,
	LEAD(decAdjClose,21) OVER (PARTITION BY strTick ORDER BY dtDate) AS OneMonthLaterClose,
	MAX(decHigh) OVER (PARTITION BY strtick ORDER BY dtDate ROWS BETWEEN  CURRENT ROW AND 21 FOLLOWING) AS OneMonthMax,
	MIN(decLow) OVER (PARTITION BY strtick ORDER BY dtDate ROWS BETWEEN  CURRENT ROW AND 21 FOLLOWING) AS OneMonthMin
FROM
	stocks
WHERE
	dtDate > '12/01/2011'
	and strTick IN('^GSPC','A','AAL','AAP','AAPL','ABBV','ABC','ABMD','ABNB','ABT','ACB','ACCD','ACES','ACIC'
	,'ACN','ADBE','ADI','ADM','ADP','ADS','ADSK','AEE','AEP','AES','AFL','AIG','AIV','AIZ','AJG','AKAM','ALB'
	,'ALGM','ALGN','ALK','ALL','ALLE','ALXN','AMAT','AMC','AMCR','AMD','AME','AMGN','AMP','AMT','AMZN','ANET'
	,'ANSS','ANTM','AON','AONE','AOS','APA','APD','APH','APHA','APTV','ARE','ARKF','ARKG','ARKK','ARKQ','ARKW'
	,'ARRY','ASAN','ASLN','ATO','ATOS','ATVI','AVB','AVGO','AVO','AVY','AWK','AXP','AZO','BA','BAC','BAX','BB'
	,'BBBY','BBKCF','BBY','BDX','BEAM','BEKE','BEN','BF.B','BIIB','BK','BKNG','BKR','BLI','BLK','BLL','BMY'
	,'BNGO','BR','BRK.A','BRK.B','BSX','BWA','BXP','BYND','C','CAG','CAH','CARR','CAT','CB','CBOE','CBRE'
	,'CCI','CCIV','CCL','CDNS','CDW','CE','CERN','CF','CFG','CGNT','CHD','CHRW','CHTR','CI','CINF','CL','CLOV'
	,'CLX','CMA','CMCSA','CME','CMG','CMI','CMS','CNC','CNP','COF','COG','COIN','COO','COP','COST','COTY','CPB'
	,'CPNG','CPRT','CRDF','CRM','CRSP','CRSR','CRWD','CSCO','CSX','CTAS','CTL','CTSH','CTVA','CTXS','CVS','CVX'
	,'CXO','D','DAL','DASH','DBTX','DD','DDD','DDS','DE','DEFTF','DFS','DG','DGX','DHI','DHR','DIS','DISCA','DISCK'
	,'DISH','DKNG','DLR','DLTR','DMTK','DOV','DOW','DPZ','DRE','DRI','DTE','DUK','DVA','DVN','DXC','DXCM','EA','EADSF'
	,'EAR','EBAY','ECL','ED','EFX','EIX','EL','EMN','EMR','ENPH','EOG','EQIX','EQR','ES','ESPR','ESS','ETFC','ETN'
	,'ETR','ETSY','EVRG','EW','EXC','EXPD','EXPE','EXPR','EXR','F','FANG','FAST','FATE','FB','FBHS','FCEL','FCX','FDX','FE','FFIV'
	,'FIS','FISV','FITB','FLIR','FLS','FLT','FMC','FNMA','FOLD','FOX','FOXA','FRC','FRT','FRX','FSLY','FSR','FTI','FTNT','FTV','FUV'
	,'GBR','GD','GE','GEO','GHVI','GILD','GIS','GL','GLD','GLW','GM','GME','GOGO','GOOG','GOOGL','GOTU','GPC','GPN','GPRO','GPS'
	,'GRMN','GS','GWW','HAL','HAS','HBAN','HBI','HCA','HD','HES','HFC','HG=F','HIG','HII','HLT','HOG','HOLX','HON','HPE','HPQ','HRB'
	,'HRL','HSIC','HST','HSY','HUM','HUTMF','HUT','IBIO','IBM','ICE','ICLN','IDXX','IEX','IFF','ILMN','INCY','INFO','INNV','INTC'
	,'INTU','IP','IPG','IPGP','IQV','IR','IRM','ISRG','IT','ITW','IVZ','J','JBHT','JCI','JKHY','JMIA','JNJ','JNPR','JPM','JWN','K'
	,'KEY','KEYS','KHC','KIM','KLAC','KMB','KMI','KMX','KO','KOSS','KR','KSS','KSU','KTOS','L','LAZR','LB','LDOS','LEG','LEN','LH'
	,'LHX','LIN','LKQ','LLY','LMND','LMT','LNC','LNT','LOW','LPRO','LRCX','LSF','LULU','LUV','LVS','LW','LYB','LYV','MA','MAA','MAR','MARA','MAS'
	,'MASS','MCD','MCHP','MCK','MCO','MCOA','MDLZ','MDT','MET','MGM','MHK','MJ','MKC','MKTX','MLM','MMC','MMM','MNMD','MNST','MO','MOS','MPC','MRK'
	,'MRO','MS','MSCI','MSFT','MSI','MSTR','MT','MTB','MTD','MU','MVIS','MXIM','MYL','NBL','NCLH','NDAQ','NEE','NEM','NFLX','NI','NIO','NKE'
	,'NKLA','NLOK','NLSN','NOC','NOV','NOW','NRG','NSC','NTAP','NTRS','NUE','NVDA','NVR','NVS','NWL','NWS','NWSA','O','OCGN','ODFL','OKE'
	,'OMC','ONEM','OPEN','ORCL','ORLY','OTIS','OXY','PATH','PAYC','PAYX','PBCT','PCAR','PEAK','PEG','PEP','PFE','PFG','PG','PGR','PH'
	,'PHM','PKG','PKI','PLD','PLL','PLTR','PM','PNC','PNR','PNW','PPG','PPL','PRGO','PRU','PSA','PSX','PTON','PUBM','PVH','PWR','PXD'
	,'PYPL','QCOM','QQQ','QRVO','RAVN','RBLX','RCL','RE','REG','REGN','RF','RHI','RIOT','RJF','RL','RMD','ROK','ROKU','ROL','ROP','ROST'
	,'RPTX','RSG','RTX','SAFRF','SBAC','SBUX','SCHW','SEDG','SEE','SEER','SENS','SHW','SIVB','SJM','SKLZ','SLB','SLG','SLV','SLVDF'
	,'SNA','SNDL','SNES','SNOW','SNPS','SNPW','SO','SOFI','SONY','SPCE','SPG','SPGI','SPXL','SPY','SQ','SRE','STE','STIC','STT','STX','STZ','SURF'
	,'SWK','SWKS','SYF','SYK','SYY','T','TAP','TDG','TEL','TER','TFC','TFX','TGT','TIF','TJX','TLRY','TMO','TMUS','TPR','TQQQ','TROW','TRV','TSCO'
	,'TSLA','TSM','TSN','TT','TTWO','TWLO','TWTR','TXN','TXT','U','UA','UAA','UAL','UDR','UHS','ULTA','UNH','UNM','UNP','UPS','URI','USB','USMJ'
	,'V','VAR','VFC','VIAC','VLDR','VLO','VMC','VNO','VRSK','VRSN','VRTX','VTR','VZ','WAB','WAT','WBA','WDC','WEC','WELL','WFC','WHR','WISH','WKHS'
	,'WLTW','WM','WMB','WMT','WOOD','WRB','WRK','WST','WU','WY','WYNN','XEL','XLB','XLC','XLE','XLF','XLI','XLK','XLNX','XLP','XLRE','XLU','XLV'
	,'XLY','XOM','XRAY','XRX','XYL','YUM','ZBH','ZBRA','ZION','ZM','ZOM','ZTS','BTC-USD','ETH-USD','ADA-USD','DOGE-USD','SHIB-USD','XLM-USD')
)  --,'^TNX','AITX','ESLT','GC=F','HWM','NAKD','NNDM','SLX','SQQQ'
,Summary
AS
(
SELECT
	dtDate,
	strTick,
	BUY_Indicator,
	SELL_Indicator,
	decAdjClose,
	OneMonthLaterClose,
	OneMonthMax,
	OneMonthMin,
	OneMonthLaterClose/decAdjClose AS GAINLOSS,
	CASE
		WHEN OneMonthLaterClose/decAdjClose >1
		THEN 1.00000
		ELSE 0.00000
	END AS UP_OR_DOWN
FROM SubQuery
WHERE
	--(
	BUY_Indicator <>0
	AND OneMonthLaterClose IS NOT NULL
	--OR SELL_Indicator <>0)
	--AND	strTick in ('BTC-USD');
)
SELECT strTick,
	AVG(UP_OR_DOWN) AS AVG_UPORDOWN,
	AVG(GAINLOSS) AS AVG_GAINLOSS,
	COUNT(*) REcordCount
FROM
	SUMMARY
GROUP BY
	strTick